---
# driver:
#   name: docker
#   use_sudo: false
#   privileged: true

# platforms:
# - name: ubuntu-18.04
#   driver_config:
#     image: ubuntu:18.04
#     platform: ubuntu

driver:
  name: vagrant
  use_sudo: false
  privileged: true

platforms:
- name: ubuntu-18.04
  driver_config:
    image: ubuntu:18.04
    platform: ubuntu

provisioner:
  name: salt_solo
  require_chef: false
  formula: filebeat
  state_top:
    base:
      '*':
        - filebeat
  pillars-from-files:
    base.sls: test-filebeat/pillar/base.sls
  pillars:
    top.sls:
      base:
        "*":
          - base

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default

verifier:
  name: inspec
